# Generated by Django 5.0.4 on 2024-07-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_alter_shippingaddress_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='Shipping_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='Shipping_address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='Shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='Shipping_country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='Shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='Shipping_full_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone_number',
            new_name='Shipping_phone_number',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='Shipping_state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_Code',
            new_name='Shipping_zip_Code',
        ),
    ]
