# Generated by Django 5.0.4 on 2024-07-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_rename_address2_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
