# Generated by Django 5.0.4 on 2024-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
