# Generated by Django 5.0.4 on 2024-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_avaliable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Avaliable',
        ),
        migrations.AddField(
            model_name='product',
            name='Not_Avaliable',
            field=models.BooleanField(default=False),
        ),
    ]
