# Generated by Django 5.0.4 on 2024-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meliCode',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
