# Generated by Django 5.0.4 on 2024-07-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_profile_old_caart2_alter_profile_old_caart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_caart2',
        ),
    ]
